# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7600703fc4d447a7d04cd08c1632c7b9041059ed010f2a244edeffc171f940d3618bc95ce127d5b54cd2efa8074e4e0c7643933fda058bd594c75a21769b56f

test:
  secret_key_base: 7c5286a51c5cb8aead3ce3d2b11b4badcacaf87827c7b45a8a0425f3898c007dd2a7d64e6964eaa06449c8da01a91c21298805353c8bca90edc492195f7b5599

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
