# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6141f957978a8daddebe6b2e41b2d56132d5f9b5f8f83479e0847606671c90fac17b37043946b3421d4f9ad73be0c41a5e2be5454aafc756f86a81fd088206d

test:
  secret_key_base: 6a60c108fcdf9f160dc34150f28239d8b8353b2b6efe5bbc2d435a6baea9de354803d706ded895909c3ac3b6e6fc1c75f5c7c4a15846e72c331a894c00d361c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
