# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b64845f7961402c95b251c1685a172762ace0dbf241c8b8b826ac8e740dc081e984a846313b180887351a1d5ab6446eb2ca0cbbc9d0939c5d5e052134fb088b7

test:
  secret_key_base: 34e519200d02cc8b8d6d756f11a4f92edf08e53a86f8c015088195f6d95a558863b8a975a05c72be122eae88f8c976832816511e7be0c98e5ba8cb179dfe95c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
