# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e3e8919188a579430803a3631e5d49e39a1c93b877409e66693cef186ba6936c6cfa30e5e402db791779e7183f1f13727d7ae07e5b149738e0e28b2ace76c10

test:
  secret_key_base: 088d7e9639b3b9a0c9fa8d9058002a6a709dc67289fe00f6a210d0caf0e29cd81ca006330e400d09517461388e8e35af869e09aa3c039e5430a898f5ddabc718

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
